Vue.component('item1', {
    props: ['opt'],
    template: '#list1'
})
Vue.component('item2', {
    props: ['poke'],
    template: '#list2'
})
Vue.component('item3', {
    props: ['paint'],
    template: '#list3'
})
Vue.component('item4', {
    props: ['poke2'],
    template: '#list4'
})
Vue.component('item5', {
    props: ['poke3'],
    template: '#list5'
})
Vue.component('item6', {
    props: ['sculpt'],
    template: '#list6'
})
Vue.component('item7', {
    props: ['movie'],
    template: '#list7'
})

var optApp = new Vue({
    el: '#head',
    data: {
        sNum: '0',
        optList: [
            { val: 'sonic', text: 'Sonic (Sonic the Hedgehog)' },
            { val: 'knuckles', text: 'Knuckles (Sonic 3 & Knuckles)' },
            { val: 'megaman', text: 'Megaman (Megaman)' },
            { val: 'megamanX', text: 'Megaman (Megaman X)' },
            { val: 'simon', text: 'Simon (Castlevania)' },
            { val: 'invader', text: 'Invader (Space Invaders)' },
            { val: 'samus', text: 'Samus (Metroid)' },
            { val: 'metroid', text: 'Metroid (Metroid)' },
            { val: 'pit', text: 'Pit (Kid Icarus)' },
            { val: 'mario', text: 'Mario (Super Mario Bros.)' },
            { val: 'mario2', text: 'Mario (Super Mario World)' },
            { val: 'marioRPG', text: 'Mario (Super Mario RPG)' },
            { val: 'gRPG', text: 'Geno (Super Mario RPG)' },
            { val: 'bowser', text: 'Bowser (Super Mario Bros.)' },
            { val: 'bowser2', text: 'Bowser (Super Mario RPG)' },
            { val: 'marioKart', text: 'Mario (Mario Kart 64)' },
            { val: 'shell1', text: 'Green Shell (Mario Kart 64)' },
            { val: 'dk', text: 'Donkey Kong (Donkey Kong Country)' },
            { val: 'yoshi', text: 'Yoshi (Super Mario World)' },
            { val: 'yoshi2', text: "Yoshi (Super Mario World 2: Yoshi's Island)" },
            { val: 'blooper', text: 'Blooper (Super Mario Bros.)' },
            { val: 'pirahna', text: 'Pirahna Plant (Super Mario Bros.)' },
            { val: 'link', text: 'Link (The Legend of Zelda)' },
            { val: 'link2', text: 'Link (The Legend of Zelda: A Link to the Past)' },
            { val: 'kirby', text: "Kirby (Kirby's Dream Land)" },
            { val: 'kirby2', text: "Kirby (Kirby's Dream Land 3)" },
            { val: 'pacman', text: 'Pac-Man (Pac-Man)' },
            { val: 'mspacman', text: 'Ms. Pac-Man (Ms. Pac-Man)' },
            { val: 'blinky', text: 'Blinky (Pac-Man)' },
            { val: 'inky', text: 'Inky (Pac-Man)' },
            { val: 'pinky', text: 'Pinky (Pac-Man)' },
            { val: 'clyde', text: 'Clyde (Pac-Man)' },
            { val: 'ghost', text: 'Ghost (Pac-Man)' },
            { val: 'excitebike', text: 'Biker (Excitebike)' },
            { val: 'frisk', text: 'Frisk (Undertale)' },
            { val: 'sans', text: 'Sans (Undertale)' },
            { val: 'kidYing', text: 'Kid Ying (The Legend of the Mystical Ninja)' },
            { val: 'drYang', text: 'Dr. Yang (The Legend of the Mystical Ninja)' },
        ],
        pokeList: [
            { val: '1', text: 'Bulbasaur/Ivysaur/Venasaur' },
            { val: '2', text: 'Charmander/Charmeleon/Charizard' },
            { val: '3', text: 'Squirtle/Wartortle/Blastoise' },
            { val: '4', text: 'Caterpie/Metapod/Butterfree' },
            { val: '5', text: 'Weedle/Kakuna/Beedrill' },
            { val: '6', text: 'Pidgey/Pidgeotto/Pidgeot' },
            { val: '7', text: 'Rattata/Raticate' },
            { val: '8', text: 'Spearow/Fearow' },
            { val: '9', text: 'Ekans/Arbok' },
            { val: '10', text: 'Pikachu/Raichu' },
            { val: '11', text: 'Sandshrew/Sandslash' },
            { val: '12', text: 'Nidoran(f)/Nidorina/Nidoqueen' },
            { val: '13', text: 'Nidoran(m)/Nidorino/Nidoking' },
            { val: '14', text: 'Clefairy/Clefable' },
            { val: '15', text: 'Vulpix/Ninetales' },
            { val: '16', text: 'Jigglypuff/Wigglytuff' },
            { val: '17', text: 'Zubat/Golbat' },
            { val: '18', text: 'Oddish/Gloom/Vileplume' },
            { val: '19', text: 'Paras/Parasect' },
            { val: '20', text: 'Venonat/Venomoth' },
            { val: '21', text: 'Diglett/Dugtrio' },
            { val: '22', text: 'Meowth/Persian' },
            { val: '23', text: 'Psyduck/Golduck' },
            { val: '24', text: 'Mankey/Primeape' },
            { val: '26', text: 'Growlithe/Arcanine' },
            { val: '27', text: 'Poliwag/Poliwhirl/Poliwrath' },
            { val: '28', text: 'Abra/Kadabra/Alakazam' },
            { val: '29', text: 'Machop/Machoke/Machamp' },
            { val: '30', text: 'Bellsprout/Weepinbell/Victreebel' },
            { val: '31', text: 'Tentacool/Tentacruel' },
            { val: '32', text: 'Geodude/Graveler/Golem' },
            { val: '33', text: 'Ponyta/Rapidash' },
            { val: '34', text: 'Slowpoke/Slowbro' },
            { val: '35', text: 'Magnemite/Magneton' },
            { val: '36', text: "Farfetch'd" },
            { val: '37', text: 'Doduo/Dodrio' },
            { val: '38', text: 'Seel/Dewgong' },
            { val: '39', text: 'Grimer/Muk' },
            { val: '40', text: 'Shellder/Cloyster' },
            { val: '41', text: 'Gastly/Haunter/Gengar' },
            { val: '42', text: 'Onix' },
            { val: '43', text: 'Drowzee/Hypno' },
            { val: '44', text: 'Krabby/Kingler' },
            { val: '45', text: 'Voltorb/Electrode' },
            { val: '46', text: 'Exeggcute/Exeggutor' },
            { val: '47', text: 'Cubone/Marowak' },
            { val: '48', text: 'Hitmonlee/Hitmonchan' },
            { val: '49', text: 'Lickitung' },
            { val: '50', text: 'Koffing/Weezing' },
            { val: '51', text: 'Rhyhorn/Rhydon' },
            { val: '52', text: 'Chansey' },
            { val: '53', text: 'Tangela' },
            { val: '54', text: 'Kangaskhan' },
            { val: '55', text: 'Horsea/Seadra' },
            { val: '56', text: 'Goldeen/Seaking' },
            { val: '57', text: 'Staryu/Starmie' },
            { val: '59', text: 'Mr. Mime' },
            { val: '60', text: 'Scyther' },
            { val: '61', text: 'Jynx' },
            { val: '62', text: 'Electabuzz' },
            { val: '63', text: 'Magmar' },
            { val: '64', text: 'Pinser' },
            { val: '65', text: 'Tauros' },
            { val: '66', text: 'Magikarp/Gyarados' },
            { val: '67', text: 'Lapras' },
            { val: '68', text: 'Ditto' },
            { val: '69', text: 'Eevee/Vaporeon/Jolteon/Flareon' },
            { val: '70', text: 'Porygon' },
            { val: '71', text: 'Omanyte/Omastar' },
            { val: '72', text: 'Kabuto/Kabutops' },
            { val: '73', text: 'Aerodactyl' },
            { val: '74', text: 'Snorlax' },
            { val: '75', text: 'Articuno/Zapdos/Moltres' },
            { val: '76', text: 'Dratini/Dragonair/Dragonite' },
            { val: '77', text: 'Mewtwo' },
            { val: '78', text: 'Mew' },
        ],
/*         pokeList2: [
            { val: '!!1', text: 'Bulbasaur/Ivysaur/Venasaur' },
            { val: '!!2', text: 'Charmander/Charmeleon/Charizard' },
            { val: '!!3', text: 'Squirtle/Wartortle/Blastoise' },
            { val: '!!4', text: 'Caterpie/Metapod/Butterfree' },
            { val: '!!5', text: 'Weedle/Kakuna/Beedrill' },
            { val: '!!6', text: 'Pidgey/Pidgeotto/Pidgeot' },
            { val: '!!7', text: 'Rattata/Raticate' },
            { val: '!!8', text: 'Spearow/Fearow' },
            { val: '!!9', text: 'Ekans/Arbok' },
            { val: '!!10', text: 'Pikachu/Raichu' },
            { val: '!!11', text: 'Sandshrew/Sandslash' },
            { val: '!!12', text: 'Nidoran(f)/Nidorina/Nidoqueen' },
            { val: '!!13', text: 'Nidoran(m)/Nidorino/Nidoking' },
            { val: '!!14', text: 'Clefairy/Clefable' },
            { val: '!!15', text: 'Vulpix/Ninetales' },
            { val: '!!16', text: 'Jigglypuff/Wigglytuff' },
            { val: '!!17', text: 'Zubat/Golbat' },
            { val: '!!18', text: 'Oddish/Gloom/Vileplume' },
            { val: '!!19', text: 'Paras/Parasect' },
            { val: '!!20', text: 'Venonat/Venomoth' },
            { val: '!!21', text: 'Diglett/Dugtrio' },
            { val: '!!22', text: 'Meowth/Persian' },
            { val: '!!23', text: 'Psyduck/Golduck' },
            { val: '!!24', text: 'Mankey/Primeape' },
            { val: '!!25', text: 'Growlithe/Arcanine' },
            { val: '!!26', text: 'Poliwag/Poliwhirl/Poliwrath' },
            { val: '!!27', text: 'Abra/Kadabra/Alakazam' },
            { val: '!!28', text: 'Machop/Machoke/Machamp' },
            { val: '!!29', text: 'Bellsprout/Weepinbell/Victreebel' },
            { val: '!!30', text: 'Tentacool/Tentacruel' },
            { val: '!!31', text: 'Geodude/Graveler/Golem' },
            { val: '!!32', text: 'Ponyta/Rapidash' },
            { val: '!!33', text: 'Slowpoke/Slowbro' },
            { val: '!!34', text: 'Magnemite/Magneton' },
            { val: '!!35', text: "Farfetch'd" },
            { val: '!!36', text: 'Doduo/Dodrio' },
            { val: '!!37', text: 'Seel/Dewgong' },
            { val: '!!38', text: 'Grimer/Muk' },
            { val: '!!39', text: 'Shellder/Cloyster' },
            { val: '!!40', text: 'Gastly/Haunter/Gengar' },
            { val: '!!41', text: 'Onix' },
            { val: '!!42', text: 'Drowzee/Hypno' },
            { val: '!!43', text: 'Krabby/Kingler' },
            { val: '!!44', text: 'Voltorb/Electrode' },
            { val: '!!45', text: 'Exeggcute/Exeggutor' },
            { val: '!!46', text: 'Cubone/Marowak' },
            { val: '!!47', text: 'Hitmonlee/Hitmonchan' },
            { val: '!!48', text: 'Lickitung' },
            { val: '!!49', text: 'Koffing/Weezing' },
            { val: '!!50', text: 'Rhyhorn/Rhydon' },
            { val: '!!51', text: 'Chansey' },
            { val: '!!52', text: 'Tangela' },
            { val: '!!53', text: 'Kangaskhan' },
            { val: '!!54', text: 'Horsea/Seadra' },
            { val: '!!55', text: 'Goldeen/Seaking' },
            { val: '!!56', text: 'Staryu/Starmie' },
            { val: '!!57', text: 'Mr. Mime' },
            { val: '!!58', text: 'Scyther' },
            { val: '!!59', text: 'Jynx' },
            { val: '!!60', text: 'Electabuzz' },
            { val: '!!61', text: 'Magmar' },
            { val: '!!62', text: 'Pinser' },
            { val: '!!63', text: 'Tauros' },
            { val: '!!64', text: 'Magikarp/Gyarados' },
            { val: '!!65', text: 'Ditto' },
            { val: '!!66', text: 'Eevee/Vaporeon/Jolteon/Flareon' },
            { val: '!!67', text: 'Porygon' },
            { val: '!!68', text: 'Omanyte/Omastar' },
            { val: '!!69', text: 'Kabuto/Kabutops' },
            { val: '!!70', text: 'Aerodactyl' },
            { val: '!!71', text: 'Snorlax' },
            { val: '!!72', text: 'Aricuno/Zapdos/Moltres' },
            { val: '!!73', text: 'Dratini/Dragonair/Dragonite' },
            { val: '!!74', text: 'Mewtwo' },
            { val: '!!75', text: 'Mew' },
        ], */
        pokeList3: [
            { val: '!1', text: 'Chikorita/Bayleef/Meganium' },
            { val: '!2', text: 'Cyndaquil/Quilava/Typhlosion' },
            { val: '!3', text: 'Totodile/Croconaw/Feraligatr' },
            { val: '!4', text: 'Sentret/Furret' },
            { val: '!5', text: 'Hoothoot/Noctowl' },
            { val: '!6', text: 'Ledyba/Ledian' },
            { val: '!7', text: 'Spinarak/Ariados' },
            { val: '!8', text: 'Crobat' },
            { val: '!9', text: 'Chinchou/Lanturn' },
            { val: '!10', text: 'Pichu' },
            { val: '!11', text: 'Cleffa' },
            { val: '!12', text: 'Igglybuff' },
            { val: '!13', text: 'Togepi/Togetic' },
            { val: '!14', text: 'Natu/Xatu' },
            { val: '!15', text: 'Mareep/Flaaffy/Ampharos' },
            { val: '!16', text: 'Bellossom' },
            { val: '!17', text: 'Marill/Azumarill' },
            { val: '!18', text: 'Sudowoodo' },
            { val: '!19', text: 'Politoed' },
            { val: '!20', text: 'Hoppip/Skiploom/Jumpluff' },
            { val: '!21', text: 'Aipom' },
            { val: '!22', text: 'Sunkern/Sunflora' },
            { val: '!23', text: 'Yanma' },
            { val: '!24', text: 'Wooper/Quagsire' },
            { val: '!25', text: 'Espeon/Umbreon' },
            { val: '!26', text: 'Murkrow' },
            { val: '!27', text: 'Slowking' },
            { val: '!28', text: 'Misdreavus' },
            { val: '!29', text: 'Unown' },
            { val: '!30', text: 'Wobbuffet' },
            { val: '!31', text: 'Girafarig' },
            { val: '!32', text: 'Pineco/Forretress' },
            { val: '!33', text: 'Dunsparce' },
            { val: '!34', text: 'Gligar' },
            { val: '!35', text: 'Steelix' },
            { val: '!36', text: 'Snubbull/Granbull' },
            { val: '!37', text: 'Qwilfish' },
            { val: '!38', text: 'Scizor' },
            { val: '!39', text: 'Shuckle' },
            { val: '!40', text: 'Heracross' },
            { val: '!41', text: 'Sneasel' },
            { val: '!42', text: 'Teddiursa/Ursaring' },
            { val: '!43', text: 'Slugma/Magcargo' },
            { val: '!44', text: 'Swinub/Piloswine' },
            { val: '!45', text: 'Corsola' },
            { val: '!46', text: 'Remoraid/Octillery' },
            { val: '!47', text: 'Delibird' },
            { val: '!48', text: 'Mantine' },
            { val: '!49', text: 'Skarmory' },
            { val: '!50', text: 'Houndour/Houndoom' },
            { val: '!51', text: 'Kingdra' },
            { val: '!52', text: 'Phanpy/Donphan' },
            { val: '!53', text: 'Porygon2' },
            { val: '!54', text: 'Stantler' },
            { val: '!55', text: 'Smeargle' },
            { val: '!56', text: 'Tyrogue/Hitmontop' },
            { val: '!57', text: 'Smoochum' },
            { val: '!58', text: 'Elekid' },
            { val: '!59', text: 'Magby' },
            { val: '!60', text: 'Miltank' },
            { val: '!61', text: 'Blissey' },
            { val: '!62', text: 'Raikou' },
            { val: '!63', text: 'Entei' },
            { val: '!64', text: 'Suicune' },
            { val: '!65', text: 'Larvitar/Pupitar/Tyranitar' },
            { val: '!66', text: 'Lugia/Ho-oh' },
            { val: '!67', text: 'Celebi' },
        ],
        paintList: [
            { val: 'monalisa', text: 'Mona Lisa by Leonardo da Vinci' },
            { val: 'gothic', text: 'American Gothic by Grant Wood' },
            { val: 'memory', text: 'The Persistence of Memory by Salvador Dali' },
            { val: 'nighthawk', text: 'Nighthawks by Edward Hopper' },
            { val: 'creationofadam', text: 'The Creation of Adam by Michelangelo' },
            { val: 'sunday', text: 'A Sunday on La Grande Jatte by Georges Seurat' },
            { val: 'pearlearring', text: 'Girl with a Pearl Earring by Johannes Vermeer' },
            { val: 'starrynight', text: 'Starry Night by Vincent Van Gogh' },
            { val: 'venus', text: 'The Birth of Venus by Sandro Boticelli' },
            
        ],
        sculptList: [
            { val: 'david', text: 'David by Michelangelo' },
            { val: 'ecstasy', text: 'Ecstasy of Saint Theresa by Bernini' },
            { val: 'laocoon', text: 'Laocoon and His Sons' },
            { val: 'discus', text: 'Discus Thrower' },
            { val: 'venus2', text: 'Venus de Milo by Alexandros' },
        ],
        movieList: [
            { val: 'matrixDodge', text: 'The Matrix (Bullet Dodge)' },
            { val: 'sparta', text: '300 (This is Sparta!)' },
            { val: 'lionKing', text: 'The Lion King (Mufasa Falls)' },
            { val: 'shining', text: "The Shining (Here's Johnny!)" }
        ],
        
    },
    methods: {
        handleSelect: function (event) {
          this.sNum = event.target.value;
          console.log(this.sNum);
        }
    }
})